#!/usr/bin/env bash

PROJECT="$1"
LABEL="$2"
if [[ -n $BLOCK_BUTTON ]]
then
  if watson status -p | grep -v "$PROJECT" > /dev/null
  then
    watson start "$PROJECT" > /dev/null
  else
    watson stop > /dev/null
  fi
fi

if watson status -p | grep -v "$PROJECT" > /dev/null
then
  echo "$LABEL"
else
  echo "<span color='Yellow'>$LABEL</span>"
fi
